### ISSUE TITLE
HELP: for some reason the search is not rendering in my terminal

### ISSUE THREAD

**Issue by Ray-Escobar** [jimeh/zsh-peco-history#12]
Hello, I have been using this extension for fairly a long time. I had to get a new laptop and now when U use zsh-peco-history (through omz) the search is rendered as image shows below: 

![image](https://github.com/user-attachments/assets/4daac5f2-831d-4984-8aa6-065151f0b62b)

This is a clean omz install, I have not really touched around fonts. Below you can find my locale file settings:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

Have you ever seen this before? Thanks in advance for any help...

**Comment by Ray-Escobar** [comment]
And if  I start typing on it, situation gets more wicked:

![image](https://github.com/user-attachments/assets/5907308c-e5c2-419a-b9e4-743e411b00f1)

**Comment by jimeh** [comment]
I've not seen this issue I'm afraid, but I also haven't used this plugin myself since I switched to `fzf` a few years ago.

But it does look similar to this issue reported on peco's repo: https://github.com/peco/peco/issues/554

Have you tried using peco manually, like `ps -aux | peco` or `history | peco`?

**Comment by Ray-Escobar** [comment]
@jimeh tahkns for response, yeah i ended up finding fzf and switched... since peco worked for what i wanted I just kept it, but fzf is indeed more powerful. 

Thanks either way

**Comment by Ray-Escobar** [comment]
@jimeh but indeed, its an issue with peco. When running it manually i get the same error. Either way not to fret here, uninstalling peco as we speak
