### ISSUE TITLE
Why is the layout hardcoded?

### ISSUE THREAD

**Issue by cyruseuros** [jimeh/zsh-peco-history#7]
`--layout=bottom-up` is unnecessary, and overrides user settings. Peco has a config file, the user should be able to make use of it. I can submit a PR if you like, but it's probably more work for you that way as well.

**Comment by cyruseuros** [comment]
Ah, shoot, already a PR in there. I guess I'll just fix the docs.

**Comment by cyruseuros** [comment]
But, there doesn't seem to be any progress on it. Will it be getting merged? If not, I can fix the docs for zplug to add `defer:2` and do that too (default environment variable and all).

**Comment by jimeh** [comment]
It's really just a left-over from the first iteration of the code. I personally prefer it, as it for the most part the command prompt will already be towards the bottom of the terminal window when there's previous output, and at which point pressing ctrl+r keeps the focus towards the bottom of the terminal.

But yes, it should definitely be configurable, with some defaults that doesn't change current behavior. I'll go ahead and merge the PR that's open later today when I've got a bit more free time, and setup defaults so the current default behavior doesn't change.

**Comment by cyruseuros** [comment]
Amazing, thanks!

**Comment by jimeh** [comment]
This should now be solved with the release of 0.10.0. If you have any issues relating to it, please feel free to re-open this issue :)
